I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/scripts/script.rpy", line 43, in script
    init python:
  File "game/scripts/script.rpy", line 43, in script
    init python:
  File "game/scripts/script.rpy", line 44, in <module>
    AddTime(15)
  File "game/scripts/relogio.rpy", line 6, in AddTime
    minutos += valorMinutos
UnboundLocalError: local variable 'minutos' referenced before assignment

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/bootstrap.py", line 326, in bootstrap
    renpy.main.main()
  File "renpy/main.py", line 515, in main
    renpy.game.context().run(node)
  File "game/scripts/script.rpy", line 43, in script
    init python:
  File "game/scripts/script.rpy", line 43, in script
    init python:
  File "renpy/ast.py", line 923, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "renpy/python.py", line 2235, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/scripts/script.rpy", line 44, in <module>
    AddTime(15)
  File "game/scripts/relogio.rpy", line 6, in AddTime
    minutos += valorMinutos
UnboundLocalError: local variable 'minutos' referenced before assignment

Windows-10-10.0.19041
Ren'Py 7.4.8.1895
ApenasTeste 1.0
Wed Oct 27 13:21:12 2021
